package lv.bootcamp.shelter.controller;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lv.bootcamp.shelter.dto.AdoptionRequest;
import lv.bootcamp.shelter.dto.AnimalCreateRequest;
import lv.bootcamp.shelter.dto.AnimalResponse;
import lv.bootcamp.shelter.service.AnimalService;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;

// Generated by GitHub Copilot
/**
 * REST controller for shelter animal operations.
 * <p>
 * Designed for MockMvc exercises:
 * - GET endpoints for listing/retrieving animals
 * - POST endpoint for creating animals (validates request body)
 * - POST endpoint for adopting animals (combines service + notification)
 */
@RestController
@RequestMapping("/api/animals")
@RequiredArgsConstructor
public class AnimalController {

    private final AnimalService animalService;

    @GetMapping
    public List<AnimalResponse> findAll() {
        return animalService.findAll();
    }

    @GetMapping("/{id}")
    public AnimalResponse findById(@PathVariable Long id) {
        return animalService.findById(id);
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public AnimalResponse create(@RequestBody @Valid AnimalCreateRequest request) {
        return animalService.create(request);
    }

    @PostMapping("/adopt")
    public AnimalResponse adopt(@RequestBody @Valid AdoptionRequest request) {
        return animalService.adopt(request);
    }

    /**
     * Deletes an animal. Restricted to ROLE_ADMIN — see SecurityConfig.
     * Purpose-built for testing role-based authorization with MockMvc:
     * see AnimalControllerSecurityTest for the ADMIN/USER/anonymous cases.
     */
    @DeleteMapping("/{id}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void delete(@PathVariable Long id) {
        animalService.delete(id);
    }
}
