package lv.bootcamp.shelter.controller;

import lombok.RequiredArgsConstructor;
import lv.bootcamp.shelter.service.AnimalService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

// Generated by GitHub Copilot
/**
 * Page controller — renders Thymeleaf views.
 * Returns view names, never JSON.
 *
 * Used to practice testing @Controller with view().name()
 * and model().attribute() instead of jsonPath().
 */
@Controller
@RequiredArgsConstructor
public class AnimalPageController {

    private final AnimalService animalService;

    /**
     * Renders the animal list page.
     * Adds all animals to the model under the key "animals".
     */
    @GetMapping("/animals")
    public String listAnimals(Model model) {
        model.addAttribute("animals", animalService.findAll());
        return "animals";
    }
}
