package lv.bootcamp.shelter.service;

// Generated by GitHub Copilot
/**
 * Thrown when a requested animal does not exist in the shelter.
 */
public class AnimalNotFoundException extends RuntimeException {

    public AnimalNotFoundException(Long id) {
        super("Animal not found: " + id);
    }
}
