package lv.bootcamp.shelter.service;

import lombok.RequiredArgsConstructor;
import lv.bootcamp.shelter.client.NotificationClient;
import lv.bootcamp.shelter.dto.AdoptionRequest;
import lv.bootcamp.shelter.dto.AnimalCreateRequest;
import lv.bootcamp.shelter.dto.AnimalResponse;
import lv.bootcamp.shelter.model.Animal;
import lv.bootcamp.shelter.model.AnimalStatus;
import lv.bootcamp.shelter.repository.AnimalRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

// Generated by GitHub Copilot
/**
 * Business logic for the shelter.
 * <p>
 * Combines repository access and external notification calls —
 * designed so students can practice Mockito tests on both seams.
 */
@Service
@RequiredArgsConstructor
public class AnimalService {

    private final AnimalRepository animalRepository;
    private final NotificationClient notificationClient;

    /**
     * Returns all animals in the shelter.
     */
    public List<AnimalResponse> findAll() {
        return animalRepository.findAll().stream()
                .map(this::toResponse)
                .toList();
    }

    /**
     * Returns a single animal by ID.
     *
     * @throws AnimalNotFoundException if no animal with the given ID exists
     */
    public AnimalResponse findById(Long id) {
        Animal animal = animalRepository.findById(id)
                .orElseThrow(() -> new AnimalNotFoundException(id));
        return toResponse(animal);
    }

    /**
     * Creates a new animal with status AVAILABLE.
     */
    @Transactional
    public AnimalResponse create(AnimalCreateRequest request) {
        Animal animal = new Animal();
        animal.setName(request.name());
        animal.setType(request.type());
        animal.setBreed(request.breed());
        animal.setAge(request.age());
        animal.setDescription(request.description());
        animal.setStatus(AnimalStatus.AVAILABLE);

        Animal saved = animalRepository.save(animal);
        return toResponse(saved);
    }

    /**
     * Marks an animal as adopted and sends an adoption notification.
     * <p>
     * This method combines database work with an external call,
     * making it a good target for integration tests that mock only
     * the notification client.
     *
     * @throws AnimalNotFoundException if the animal does not exist
     * @throws IllegalStateException if the animal is not available for adoption
     */
    @Transactional
    public AnimalResponse adopt(AdoptionRequest request) {
        Animal animal = animalRepository.findById(request.animalId())
                .orElseThrow(() -> new AnimalNotFoundException(request.animalId()));

        if (animal.getStatus() != AnimalStatus.AVAILABLE) {
            throw new IllegalStateException(
                    "Animal %d is not available for adoption (current status: %s)"
                            .formatted(animal.getId(), animal.getStatus()));
        }

        animal.setStatus(AnimalStatus.ADOPTED);
        Animal saved = animalRepository.save(animal);

        notificationClient.sendAdoptionNotification(
                saved.getId(), saved.getName(), request.adopterEmail());

        return toResponse(saved);
    }

    private AnimalResponse toResponse(Animal animal) {
        return new AnimalResponse(
                animal.getId(),
                animal.getName(),
                animal.getType(),
                animal.getBreed(),
                animal.getAge(),
                animal.getDescription(),
                animal.getStatus()
        );
    }

    /**
     * Deletes an animal by ID.
     * <p>
     * Restricted to ROLE_ADMIN in {@code SecurityConfig} — a good target for
     * MockMvc security tests: authorized role succeeds, wrong role gets 403,
     * no auth gets 401 (see {@code AnimalControllerSecurityTest}).
     *
     * @throws AnimalNotFoundException if no animal with the given ID exists
     */
    @Transactional
    public void delete(Long id) {
        if (!animalRepository.existsById(id)) {
            throw new AnimalNotFoundException(id);
        }
        animalRepository.deleteById(id);
    }

    /**
     * Reserves multiple animals at once and notifies an external system
     * with the list of affected IDs.
     * <p>
     * Good @Captor target: the service builds a list internally and passes it
     * to a void method. Students must capture the list to assert its contents.
     *
     * @throws IllegalStateException if any animal is not AVAILABLE
     */
    @Transactional
    public List<AnimalResponse> reserveMultiple(List<Long> animalIds) {
        List<Animal> animals = animalRepository.findAllById(animalIds);

        if (animals.size() != animalIds.size()) {
            throw new AnimalNotFoundException(
                    animalIds.stream()
                            .filter(id -> animals.stream().noneMatch(a -> a.getId().equals(id)))
                            .findFirst().orElse(0L));
        }

        List<Long> reservedIds = animals.stream()
                .peek(animal -> {
                    if (animal.getStatus() != AnimalStatus.AVAILABLE) {
                        throw new IllegalStateException(
                                "Animal %d is not available".formatted(animal.getId()));
                    }
                    animal.setStatus(AnimalStatus.RESERVED);
                })
                .map(animalRepository::save)
                .map(Animal::getId)
                .collect(Collectors.toList());

        notificationClient.sendBulkStatusNotification(reservedIds, "RESERVED");

        return animals.stream().map(this::toResponse).toList();
    }
}
