package lv.bootcamp.shelter.dto;

import lv.bootcamp.shelter.model.AnimalStatus;
import lv.bootcamp.shelter.model.AnimalType;

// Generated by GitHub Copilot
/**
 * Response representation of an animal in the shelter.
 */
public record AnimalResponse(
        Long id,
        String name,
        AnimalType type,
        String breed,
        Integer age,
        String description,
        AnimalStatus status
) {
}
