package lv.bootcamp.shelter.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lv.bootcamp.shelter.model.AnimalType;

// Generated by GitHub Copilot
/**
 * Request body for creating a new animal in the shelter.
 */
public record AnimalCreateRequest(
        @NotBlank String name,
        @NotNull AnimalType type,
        String breed,
        @Min(0) Integer age,
        String description
) {
}
