package lv.bootcamp.shelter.repository;

import lv.bootcamp.shelter.model.Animal;
import lv.bootcamp.shelter.model.AnimalStatus;
import lv.bootcamp.shelter.model.AnimalType;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

// Generated by GitHub Copilot
/**
 * Spring Data JPA repository for Animal entities.
 * Provides derived queries used in @DataJpaTest exercises.
 */
public interface AnimalRepository extends JpaRepository<Animal, Long> {

    List<Animal> findByStatus(AnimalStatus status);

    List<Animal> findByType(AnimalType type);

    List<Animal> findByNameContainingIgnoreCase(String name);
}
