package lv.bootcamp.shelter.client;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.List;

// Generated by GitHub Copilot
/**
 * Default implementation of NotificationClient.
 * Logs instead of calling a real external service.
 * <p>
 * In integration tests this bean is commonly replaced by @MockitoBean.
 */
@Slf4j
@Component
public class LoggingNotificationClient implements NotificationClient {

    @Override
    public void sendAdoptionNotification(Long animalId, String animalName, String adopterEmail) {
        log.info("Adoption notification: animal {} ({}) adopted — notifying {}",
                animalId, animalName, adopterEmail);
    }

    @Override
    public void sendBulkStatusNotification(List<Long> animalIds, String newStatus) {
        log.info("Bulk status notification: {} animal(s) changed to {} — ids: {}",
                animalIds.size(), newStatus, animalIds);
    }
}
