package lv.bootcamp.shelter.client;

import java.util.List;

// Generated by GitHub Copilot
/**
 * External dependency seam: sends adoption notifications to an external system.
 * <p>
 * In production this would call a remote service (email, SMS, webhook).
 * In tests this interface is mocked with @MockitoBean to verify that the service
 * triggers notifications without making real external calls.
 */
public interface NotificationClient {

    /**
     * Sends an adoption notification for the given animal.
     *
     * @param animalId   the adopted animal's ID
     * @param animalName the adopted animal's name
     * @param adopterEmail the adopter's contact email
     */
    void sendAdoptionNotification(Long animalId, String animalName, String adopterEmail);

    /**
     * Sends a bulk status-change notification for multiple animals.
     *
     * @param animalIds list of animal IDs whose status changed
     * @param newStatus the new status label
     */
    void sendBulkStatusNotification(List<Long> animalIds, String newStatus);
}
