package lv.bootcamp.shelter.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.Customizer;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.provisioning.InMemoryUserDetailsManager;
import org.springframework.security.web.SecurityFilterChain;

// Generated by GitHub Copilot
/**
 * Baseline Spring Security setup for the shelter-testing starter project.
 *
 * <ul>
 *   <li>Two in-memory demo accounts, with deliberately separate roles:
 *       {@code user}/{@code user123} (ROLE_USER only) and
 *       {@code admin}/{@code admin123} (ROLE_ADMIN only).</li>
 *   <li>Anyone (including anonymous visitors) can browse {@code /animals} and
 *       read/write the API ({@code GET}/{@code POST /api/animals/**}) \u2014 this
 *       keeps the existing MockMvc tests (which don't use
 *       {@code @WithMockUser}) working unchanged.</li>
 *   <li>Only ROLE_ADMIN can delete an animal ({@code DELETE /api/animals/{id}}) \u2014
 *       a purpose-built restricted endpoint so students have something to
 *       exercise with {@code @WithMockUser(roles = "ADMIN"/"USER")} and an
 *       anonymous (no-auth) request. See {@code AnimalControllerSecurityTest}.</li>
 *   <li>Uses HTTP Basic auth; the JSON API is exercised directly
 *       (curl/Postman/MockMvc), so CSRF protection is not needed there.</li>
 * </ul>
 *
 * <p><b>Optional bonus (ungraded, not checked):</b> swap HTTP Basic for JWT on
 * {@code /api/**}, then test the filter itself instead of relying on
 * {@code @WithMockUser}. This adds real complexity and is intentionally kept
 * out of the core practical task \u2014 see the module notes on Slide 14/24 for
 * why, and see Task_M12's {@code SecurityConfig} for a worked JWT bonus example
 * if you want to attempt it anyway:
 * <ol>
 *   <li>Add a {@code POST /api/auth/login} endpoint that authenticates via
 *       {@code AuthenticationManager} and returns a signed JWT.</li>
 *   <li>Write a {@code JwtAuthFilter} ({@code OncePerRequestFilter}) that reads
 *       the {@code Authorization: Bearer <token>} header and populates the
 *       {@code SecurityContextHolder}.</li>
 *   <li>Unit-test the filter directly (mock {@code JwtService} +
 *       {@code FilterChain}) rather than trying to drive it through a
 *       {@code @WebMvcTest} slice.</li>
 * </ol>
 */
@Configuration
public class SecurityConfig {

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Bean
    public InMemoryUserDetailsManager userDetailsService(PasswordEncoder passwordEncoder) {
        UserDetails user = User.builder()
                .username("user")
                .password(passwordEncoder.encode("user123"))
                .roles("USER")
                .build();

        UserDetails admin = User.builder()
                .username("admin")
                .password(passwordEncoder.encode("admin123"))
                .roles("ADMIN")
                .build();

        return new InMemoryUserDetailsManager(user, admin);
    }

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
                .csrf(csrf -> csrf.ignoringRequestMatchers("/api/**"))
                .authorizeHttpRequests(auth -> auth
                        .requestMatchers(HttpMethod.DELETE, "/api/animals/**").hasRole("ADMIN")
                        .requestMatchers("/api/animals/**").permitAll()
                        .requestMatchers("/animals", "/animals/**").permitAll()
                        .anyRequest().authenticated()
                )
                .httpBasic(Customizer.withDefaults())
                .formLogin(Customizer.withDefaults());

        return http.build();
    }
}
