package lv.bootcamp.shelter;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// Generated by GitHub Copilot
@SpringBootApplication
public class ShelterTestingApplication {

    public static void main(String[] args) {
        SpringApplication.run(ShelterTestingApplication.class, args);
    }
}
